---
- name: Update APT cache
  apt: update_cache=yes

- name: Ensure dependencies are installed
  apt: "pkg={{ item }} state=present"
  with_items:
    - build-essential
    - autoconf
    - automake
    - libtool

- name: Clone libsass repository
  git:
    repo: https://github.com/sass/libsass.git
    dest: /usr/src/libsass
    accept_hostkey: yes
    depth: 1
    force: yes

- name: Generate configure script
  shell: autoreconf --force --install chdir=/usr/src/libsass

- name: Configure libsass compilation
  shell: >
    ./configure
    --disable-tests
    --enable-shared
    --prefix=/usr
    chdir=/usr/src/libsass

- name: Build libsass
  shell: make --jobs={{ ansible_processor_cores }} chdir=/usr/src/libsass

- name: Install libsass
  shell: make install chdir=/usr/src/libsass